config/routes.rb
Rails.application.routes.draw do
  # http  location   controller#method  route alias
  get '/landing', to: 'home#landing', as: 'landing'
  get '/oyster', to: 'home#oyster', as: 'oyster'
  get '/enchiladas', to: 'home#enchiladas', as: 'enchiladas'
  get '/github_user/:user/:logged_in', to: 'github_mock#github_user' 
  # specifies which method should run at the base url '/'
  root 'home#landing'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/github_mock_controller.rb
class GithubMockController < ApplicationController
  def github_user
    @logged_in = params[:logged_in]
    if @logged_in === 'true'
      @user = params[:user]
    else 
      @user = 'please log in'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def landing
    @greeter = 'Hello Alpha!'
  end
  def oyster
  end
  def enchiladas
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/github_mock/github_user.html.erb
<h1>GitHub Mock</h1>
<p>Hello!</p>
<p><%= @user %></p>
<p>Are you logged in? <%= @logged_in %></p>

app/views/home/enchiladas.html.erb
<h1>Enchiladas are great!</h1>
<%= link_to 'Home', landing_path %>

app/views/home/landing.html.erb
<h1>yo!</h1>
<h3 class="greeter"><%= @greeter %></h3>
<%= link_to 'Oyster Bar', oyster_path %>

app/views/home/oyster.html.erb
<h1>Welcome to our Oyster bar</h1>
<h3>Oysters are slimy and delicious</h3>
<%= link_to 'Home', landing_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Params</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %> 
    <%= csp_meta_tag %> 
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> 
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>